const Themes = {
  logo: {
    backgroundColor: "black",
    gridColumn: 2,
    filter: "invert(100%)",
    size: "100%",
    marginTop: "3%",
    marginBottom: "3%",
  },
  item: {
    height: "2em",
    width: "80%",
    marginLeft: "10%",
    marginTop: "0.5em",
    backgroundColor: "#163B6E",
    color: "#FDF551",
    fontSize: "2em",
    border: "none",
    fontWeight: "bold",
    fontFamily: "Nunito",
  },
  create: {
    height: "2em",
    width: "40%",
    marginLeft: "10%",
    marginTop: "0.5em",
    backgroundColor: "#FDF551",
    color: "black",
    fontSize: "2em",
    border: "none",
    fontWeight: "bold",
    fontFamily: "Nunito",
  },
};
export default Themes;
